### PR TITLE
Add zetachain testnet

### PR DESCRIPTION
**Pull request by siddharth-leap**
cc @fadeev

### CODE REVIEW

**Comment by fadeev** [comment]
I'm getting the same error when trying to send tokens.

**Comment by fadeev** [comment]
zetachain-icon@4x

#043829

**Comment by fadeev** [comment]
I'm fairly sure the issue has nothing to do with the blockchain, because I've added ZetaChain to Ping.Pub and Keplr sucessfuly.

**Comment by siddharth-leap** [comment]
@fadeev The issue is not on your end, it is an issue with Leap Wallet extension. We have found the issue and we're shipping the fix in the next release.

**Comment by fadeev** [comment]
@siddharth-leap do you have a date when you think the updated version of the extension will be released on the Google Chrome extension store?

**Pull request merged**
